controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # 虚拟左臂控制器
    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    # 虚拟右臂控制器
    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    # 虚拟夹爪控制器
    left_hand_controller:
      type: gripper_controllers/GripperActionController
    right_hand_controller:
      type: gripper_controllers/GripperActionController

# 左臂控制器配置
left_arm_controller:
  ros__parameters:
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    interface_name: position
    action_monitor_rate: 20.0

# 右臂控制器配置
right_arm_controller:
  ros__parameters:
    joints:
      - openarm_right_joint1
      - openarm_right_joint2
      - openarm_right_joint3
      - openarm_right_joint4
      - openarm_right_joint5
      - openarm_right_joint6
      - openarm_right_joint7
    interface_name: position
    action_monitor_rate: 20.0

# 左夹爪控制器配置
left_hand_controller:
  ros__parameters:
    joint: openarm_left_finger_joint1
    action_monitor_rate: 20.0

# 右夹爪控制器配置
right_hand_controller:
  ros__parameters:
    joint: openarm_right_finger_joint1
    action_monitor_rate: 20.0
